deamon:
  pid_file: ./tanke.pid
log:
  log_level: debug
  log_file: log/tanke.log
  log_format: text # json -> to output in json format
database:
  host: localhost
  port: 5432
  user: admin
  password: admin
  database: postgres
