INSERT INTO wfg.country VALUES (1, 'Afghanistan', 'Afganistán', 'AF', 'AFG', '93');
INSERT INTO wfg.country VALUES (2, 'Albania', 'Albania', 'AL', 'ALB', '355');
INSERT INTO wfg.country VALUES (3, 'Germany', 'Alemania', 'DE', 'DEU', '49');
INSERT INTO wfg.country VALUES (4, 'Andorra', 'Andorra', 'AD', 'AND', '376');
INSERT INTO wfg.country VALUES (5, 'Angola', 'Angola', 'AO', 'AGO', '244');
INSERT INTO wfg.country VALUES (6, 'Anguilla', 'Anguila', 'AI', 'AIA', '1 264');
INSERT INTO wfg.country VALUES (7, 'Antarctica', 'Antártida', 'AQ', 'ATA', '672');
INSERT INTO wfg.country VALUES (8, 'Antigua and Barbuda', 'Antigua y Barbuda', 'AG', 'ATG', '1 268');
INSERT INTO wfg.country VALUES (9, 'Saudi Arabia', 'Arabia Saudita', 'SA', 'SAU', '966');
INSERT INTO wfg.country VALUES (10, 'Algeria', 'Argelia', 'DZ', 'DZA', '213');
INSERT INTO wfg.country VALUES (11, 'Argentina', 'Argentina', 'AR', 'ARG', '54');
INSERT INTO wfg.country VALUES (12, 'Armenia', 'Armenia', 'AM', 'ARM', '374');
INSERT INTO wfg.country VALUES (13, 'Aruba', 'Aruba', 'AW', 'ABW', '297');
INSERT INTO wfg.country VALUES (14, 'Australia', 'Australia', 'AU', 'AUS', '61');
INSERT INTO wfg.country VALUES (15, 'Austria', 'Austria', 'AT', 'AUT', '43');
INSERT INTO wfg.country VALUES (16, 'Azerbaijan', 'Azerbaiyán', 'AZ', 'AZE', '994');
INSERT INTO wfg.country VALUES (17, 'Belgium', 'Bélgica', 'BE', 'BEL', '32');
INSERT INTO wfg.country VALUES (18, 'Bahamas', 'Bahamas', 'BS', 'BHS', '1 242');
INSERT INTO wfg.country VALUES (19, 'Bahrain', 'Bahrein', 'BH', 'BHR', '973');
INSERT INTO wfg.country VALUES (20, 'Bangladesh', 'Bangladesh', 'BD', 'BGD', '880');
INSERT INTO wfg.country VALUES (21, 'Barbados', 'Barbados', 'BB', 'BRB', '1 246');
INSERT INTO wfg.country VALUES (22, 'Belize', 'Belice', 'BZ', 'BLZ', '501');
INSERT INTO wfg.country VALUES (23, 'Benin', 'Benín', 'BJ', 'BEN', '229');
INSERT INTO wfg.country VALUES (24, 'Bhutan', 'Bhután', 'BT', 'BTN', '975');
INSERT INTO wfg.country VALUES (25, 'Belarus', 'Bielorrusia', 'BY', 'BLR', '375');
INSERT INTO wfg.country VALUES (26, 'Myanmar', 'Birmania', 'MM', 'MMR', '95');
INSERT INTO wfg.country VALUES (27, 'Bolivia', 'Bolivia', 'BO', 'BOL', '591');
INSERT INTO wfg.country VALUES (28, 'Bosnia and Herzegovina', 'Bosnia y Herzegovina', 'BA', 'BIH', '387');
INSERT INTO wfg.country VALUES (29, 'Botswana', 'Botsuana', 'BW', 'BWA', '267');
INSERT INTO wfg.country VALUES (30, 'Brazil', 'Brasil', 'BR', 'BRA', '55');
INSERT INTO wfg.country VALUES (31, 'Brunei', 'Brunéi', 'BN', 'BRN', '673');
INSERT INTO wfg.country VALUES (32, 'Bulgaria', 'Bulgaria', 'BG', 'BGR', '359');
INSERT INTO wfg.country VALUES (33, 'Burkina Faso', 'Burkina Faso', 'BF', 'BFA', '226');
INSERT INTO wfg.country VALUES (34, 'Burundi', 'Burundi', 'BI', 'BDI', '257');
INSERT INTO wfg.country VALUES (35, 'Cape Verde', 'Cabo Verde', 'CV', 'CPV', '238');
INSERT INTO wfg.country VALUES (36, 'Cambodia', 'Camboya', 'KH', 'KHM', '855');
INSERT INTO wfg.country VALUES (37, 'Cameroon', 'Camerún', 'CM', 'CMR', '237');
INSERT INTO wfg.country VALUES (38, 'Canada', 'Canadá', 'CA', 'CAN', '1');
INSERT INTO wfg.country VALUES (39, 'Chad', 'Chad', 'TD', 'TCD', '235');
INSERT INTO wfg.country VALUES (40, 'Chile', 'Chile', 'CL', 'CHL', '56');
INSERT INTO wfg.country VALUES (41, 'China', 'China', 'CN', 'CHN', '86');
INSERT INTO wfg.country VALUES (42, 'Cyprus', 'Chipre', 'CY', 'CYP', '357');
INSERT INTO wfg.country VALUES (43, 'Vatican City State', 'Ciudad del Vaticano', 'VA', 'VAT', '39');
INSERT INTO wfg.country VALUES (44, 'Colombia', 'Colombia', 'CO', 'COL', '57');
INSERT INTO wfg.country VALUES (45, 'Comoros', 'Comoras', 'KM', 'COM', '269');
INSERT INTO wfg.country VALUES (46, 'Republic of the Congo', 'República del Congo', 'CG', 'COG', '242');
INSERT INTO wfg.country VALUES (47, 'Democratic Republic of the Congo', 'República Democrática del Congo', 'CD', 'COD', '243');
INSERT INTO wfg.country VALUES (48, 'North Korea', 'Corea del Norte', 'KP', 'PRK', '850');
INSERT INTO wfg.country VALUES (49, 'South Korea', 'Corea del Sur', 'KR', 'KOR', '82');
INSERT INTO wfg.country VALUES (50, 'Ivory Coast', 'Costa de Marfil', 'CI', 'CIV', '225');
INSERT INTO wfg.country VALUES (51, 'Costa Rica', 'Costa Rica', 'CR', 'CRI', '506');
INSERT INTO wfg.country VALUES (52, 'Croatia', 'Croacia', 'HR', 'HRV', '385');
INSERT INTO wfg.country VALUES (53, 'Cuba', 'Cuba', 'CU', 'CUB', '53');
INSERT INTO wfg.country VALUES (54, 'Curaçao', 'Curazao', 'CW', 'CWU', '5999');
INSERT INTO wfg.country VALUES (55, 'Denmark', 'Dinamarca', 'DK', 'DNK', '45');
INSERT INTO wfg.country VALUES (56, 'Dominica', 'Dominica', 'DM', 'DMA', '1 767');
INSERT INTO wfg.country VALUES (57, 'Ecuador', 'Ecuador', 'EC', 'ECU', '593');
INSERT INTO wfg.country VALUES (58, 'Egypt', 'Egipto', 'EG', 'EGY', '20');
INSERT INTO wfg.country VALUES (59, 'El Salvador', 'El Salvador', 'SV', 'SLV', '503');
INSERT INTO wfg.country VALUES (60, 'United Arab Emirates', 'Emiratos Árabes Unidos', 'AE', 'ARE', '971');
INSERT INTO wfg.country VALUES (61, 'Eritrea', 'Eritrea', 'ER', 'ERI', '291');
INSERT INTO wfg.country VALUES (62, 'Slovakia', 'Eslovaquia', 'SK', 'SVK', '421');
INSERT INTO wfg.country VALUES (63, 'Slovenia', 'Eslovenia', 'SI', 'SVN', '386');
INSERT INTO wfg.country VALUES (64, 'Spain', 'España', 'ES', 'ESP', '34');
INSERT INTO wfg.country VALUES (65, 'United States of America', 'Estados Unidos de América', 'US', 'USA', '1');
INSERT INTO wfg.country VALUES (66, 'Estonia', 'Estonia', 'EE', 'EST', '372');
INSERT INTO wfg.country VALUES (67, 'Ethiopia', 'Etiopía', 'ET', 'ETH', '251');
INSERT INTO wfg.country VALUES (68, 'Philippines', 'Filipinas', 'PH', 'PHL', '63');
INSERT INTO wfg.country VALUES (69, 'Finland', 'Finlandia', 'FI', 'FIN', '358');
INSERT INTO wfg.country VALUES (70, 'Fiji', 'Fiyi', 'FJ', 'FJI', '679');
INSERT INTO wfg.country VALUES (71, 'France', 'Francia', 'FR', 'FRA', '33');
INSERT INTO wfg.country VALUES (72, 'Gabon', 'Gabón', 'GA', 'GAB', '241');
INSERT INTO wfg.country VALUES (73, 'Gambia', 'Gambia', 'GM', 'GMB', '220');
INSERT INTO wfg.country VALUES (74, 'Georgia', 'Georgia', 'GE', 'GEO', '995');
INSERT INTO wfg.country VALUES (75, 'Ghana', 'Ghana', 'GH', 'GHA', '233');
INSERT INTO wfg.country VALUES (76, 'Gibraltar', 'Gibraltar', 'GI', 'GIB', '350');
INSERT INTO wfg.country VALUES (77, 'Grenada', 'Granada', 'GD', 'GRD', '1 473');
INSERT INTO wfg.country VALUES (78, 'Greece', 'Grecia', 'GR', 'GRC', '30');
INSERT INTO wfg.country VALUES (79, 'Greenland', 'Groenlandia', 'GL', 'GRL', '299');
INSERT INTO wfg.country VALUES (80, 'Guadeloupe', 'Guadalupe', 'GP', 'GLP', '590');
INSERT INTO wfg.country VALUES (81, 'Guam', 'Guam', 'GU', 'GUM', '1 671');
INSERT INTO wfg.country VALUES (82, 'Guatemala', 'Guatemala', 'GT', 'GTM', '502');
INSERT INTO wfg.country VALUES (83, 'French Guiana', 'Guayana Francesa', 'GF', 'GUF', '594');
INSERT INTO wfg.country VALUES (84, 'Guernsey', 'Guernsey', 'GG', 'GGY', '44');
INSERT INTO wfg.country VALUES (85, 'Guinea', 'Guinea', 'GN', 'GIN', '224');
INSERT INTO wfg.country VALUES (86, 'Equatorial Guinea', 'Guinea Ecuatorial', 'GQ', 'GNQ', '240');
INSERT INTO wfg.country VALUES (87, 'Guinea-Bissau', 'Guinea-Bissau', 'GW', 'GNB', '245');
INSERT INTO wfg.country VALUES (88, 'Guyana', 'Guyana', 'GY', 'GUY', '592');
INSERT INTO wfg.country VALUES (89, 'Haiti', 'Haití', 'HT', 'HTI', '509');
INSERT INTO wfg.country VALUES (90, 'Honduras', 'Honduras', 'HN', 'HND', '504');
INSERT INTO wfg.country VALUES (91, 'Hong Kong', 'Hong kong', 'HK', 'HKG', '852');
INSERT INTO wfg.country VALUES (92, 'Hungary', 'Hungría', 'HU', 'HUN', '36');
INSERT INTO wfg.country VALUES (93, 'India', 'India', 'IN', 'IND', '91');
INSERT INTO wfg.country VALUES (94, 'Indonesia', 'Indonesia', 'ID', 'IDN', '62');
INSERT INTO wfg.country VALUES (95, 'Iran', 'Irán', 'IR', 'IRN', '98');
INSERT INTO wfg.country VALUES (96, 'Iraq', 'Irak', 'IQ', 'IRQ', '964');
INSERT INTO wfg.country VALUES (97, 'Ireland', 'Irlanda', 'IE', 'IRL', '353');
INSERT INTO wfg.country VALUES (98, 'Bouvet Island', 'Isla Bouvet', 'BV', 'BVT', NULL);
INSERT INTO wfg.country VALUES (99, 'Isle of Man', 'Isla de Man', 'IM', 'IMN', '44');
INSERT INTO wfg.country VALUES (100, 'Christmas Island', 'Isla de Navidad', 'CX', 'CXR', '61');
INSERT INTO wfg.country VALUES (101, 'Norfolk Island', 'Isla Norfolk', 'NF', 'NFK', '672');
INSERT INTO wfg.country VALUES (102, 'Iceland', 'Islandia', 'IS', 'ISL', '354');
INSERT INTO wfg.country VALUES (103, 'Bermuda Islands', 'Islas Bermudas', 'BM', 'BMU', '1 441');
INSERT INTO wfg.country VALUES (104, 'Cayman Islands', 'Islas Caimán', 'KY', 'CYM', '1 345');
INSERT INTO wfg.country VALUES (105, 'Cocos (Keeling) Islands', 'Islas Cocos (Keeling)', 'CC', 'CCK', '61');
INSERT INTO wfg.country VALUES (106, 'Cook Islands', 'Islas Cook', 'CK', 'COK', '682');
INSERT INTO wfg.country VALUES (107, 'Åland Islands', 'Islas de Åland', 'AX', 'ALA', '358');
INSERT INTO wfg.country VALUES (108, 'Faroe Islands', 'Islas Feroe', 'FO', 'FRO', '298');
INSERT INTO wfg.country VALUES (109, 'South Georgia and the South Sandwich Islands', 'Islas Georgias del Sur y Sandwich del Sur', 'GS', 'SGS', '500');
INSERT INTO wfg.country VALUES (110, 'Heard Island and McDonald Islands', 'Islas Heard y McDonald', 'HM', 'HMD', NULL);
INSERT INTO wfg.country VALUES (111, 'Maldives', 'Islas Maldivas', 'MV', 'MDV', '960');
INSERT INTO wfg.country VALUES (112, 'Falkland Islands (Malvinas)', 'Islas Malvinas', 'FK', 'FLK', '500');
INSERT INTO wfg.country VALUES (113, 'Northern Mariana Islands', 'Islas Marianas del Norte', 'MP', 'MNP', '1 670');
INSERT INTO wfg.country VALUES (114, 'Marshall Islands', 'Islas Marshall', 'MH', 'MHL', '692');
INSERT INTO wfg.country VALUES (115, 'Pitcairn Islands', 'Islas Pitcairn', 'PN', 'PCN', '870');
INSERT INTO wfg.country VALUES (116, 'Solomon Islands', 'Islas Salomón', 'SB', 'SLB', '677');
INSERT INTO wfg.country VALUES (117, 'Turks and Caicos Islands', 'Islas Turcas y Caicos', 'TC', 'TCA', '1 649');
INSERT INTO wfg.country VALUES (234, 'Turkmenistan', 'Turkmenistán', 'TM', 'TKM', '993');
INSERT INTO wfg.country VALUES (118, 'United States Minor Outlying Islands', 'Islas Ultramarinas Menores de Estados Unidos', 'UM', 'UMI', '246');
INSERT INTO wfg.country VALUES (119, 'Virgin Islands', 'Islas Vírgenes Británicas', 'VG', 'VGB', '1 284');
INSERT INTO wfg.country VALUES (120, 'United States Virgin Islands', 'Islas Vírgenes de los Estados Unidos', 'VI', 'VIR', '1 340');
INSERT INTO wfg.country VALUES (121, 'Israel', 'Israel', 'IL', 'ISR', '972');
INSERT INTO wfg.country VALUES (122, 'Italy', 'Italia', 'IT', 'ITA', '39');
INSERT INTO wfg.country VALUES (123, 'Jamaica', 'Jamaica', 'JM', 'JAM', '1 876');
INSERT INTO wfg.country VALUES (124, 'Japan', 'Japón', 'JP', 'JPN', '81');
INSERT INTO wfg.country VALUES (125, 'Jersey', 'Jersey', 'JE', 'JEY', '44');
INSERT INTO wfg.country VALUES (126, 'Jordan', 'Jordania', 'JO', 'JOR', '962');
INSERT INTO wfg.country VALUES (127, 'Kazakhstan', 'Kazajistán', 'KZ', 'KAZ', '7');
INSERT INTO wfg.country VALUES (128, 'Kenya', 'Kenia', 'KE', 'KEN', '254');
INSERT INTO wfg.country VALUES (129, 'Kyrgyzstan', 'Kirguistán', 'KG', 'KGZ', '996');
INSERT INTO wfg.country VALUES (130, 'Kiribati', 'Kiribati', 'KI', 'KIR', '686');
INSERT INTO wfg.country VALUES (131, 'Kuwait', 'Kuwait', 'KW', 'KWT', '965');
INSERT INTO wfg.country VALUES (132, 'Lebanon', 'Líbano', 'LB', 'LBN', '961');
INSERT INTO wfg.country VALUES (133, 'Laos', 'Laos', 'LA', 'LAO', '856');
INSERT INTO wfg.country VALUES (134, 'Lesotho', 'Lesoto', 'LS', 'LSO', '266');
INSERT INTO wfg.country VALUES (135, 'Latvia', 'Letonia', 'LV', 'LVA', '371');
INSERT INTO wfg.country VALUES (136, 'Liberia', 'Liberia', 'LR', 'LBR', '231');
INSERT INTO wfg.country VALUES (137, 'Libya', 'Libia', 'LY', 'LBY', '218');
INSERT INTO wfg.country VALUES (138, 'Liechtenstein', 'Liechtenstein', 'LI', 'LIE', '423');
INSERT INTO wfg.country VALUES (139, 'Lithuania', 'Lituania', 'LT', 'LTU', '370');
INSERT INTO wfg.country VALUES (140, 'Luxembourg', 'Luxemburgo', 'LU', 'LUX', '352');
INSERT INTO wfg.country VALUES (141, 'Mexico', 'México', 'MX', 'MEX', '52');
INSERT INTO wfg.country VALUES (142, 'Monaco', 'Mónaco', 'MC', 'MCO', '377');
INSERT INTO wfg.country VALUES (143, 'Macao', 'Macao', 'MO', 'MAC', '853');
INSERT INTO wfg.country VALUES (144, 'Macedonia', 'Macedônia', 'MK', 'MKD', '389');
INSERT INTO wfg.country VALUES (145, 'Madagascar', 'Madagascar', 'MG', 'MDG', '261');
INSERT INTO wfg.country VALUES (146, 'Malaysia', 'Malasia', 'MY', 'MYS', '60');
INSERT INTO wfg.country VALUES (147, 'Malawi', 'Malawi', 'MW', 'MWI', '265');
INSERT INTO wfg.country VALUES (148, 'Mali', 'Mali', 'ML', 'MLI', '223');
INSERT INTO wfg.country VALUES (149, 'Malta', 'Malta', 'MT', 'MLT', '356');
INSERT INTO wfg.country VALUES (150, 'Morocco', 'Marruecos', 'MA', 'MAR', '212');
INSERT INTO wfg.country VALUES (151, 'Martinique', 'Martinica', 'MQ', 'MTQ', '596');
INSERT INTO wfg.country VALUES (152, 'Mauritius', 'Mauricio', 'MU', 'MUS', '230');
INSERT INTO wfg.country VALUES (153, 'Mauritania', 'Mauritania', 'MR', 'MRT', '222');
INSERT INTO wfg.country VALUES (154, 'Mayotte', 'Mayotte', 'YT', 'MYT', '262');
INSERT INTO wfg.country VALUES (155, 'Estados Federados de', 'Micronesia', 'FM', 'FSM', '691');
INSERT INTO wfg.country VALUES (156, 'Moldova', 'Moldavia', 'MD', 'MDA', '373');
INSERT INTO wfg.country VALUES (157, 'Mongolia', 'Mongolia', 'MN', 'MNG', '976');
INSERT INTO wfg.country VALUES (158, 'Montenegro', 'Montenegro', 'ME', 'MNE', '382');
INSERT INTO wfg.country VALUES (159, 'Montserrat', 'Montserrat', 'MS', 'MSR', '1 664');
INSERT INTO wfg.country VALUES (160, 'Mozambique', 'Mozambique', 'MZ', 'MOZ', '258');
INSERT INTO wfg.country VALUES (161, 'Namibia', 'Namibia', 'NA', 'NAM', '264');
INSERT INTO wfg.country VALUES (162, 'Nauru', 'Nauru', 'NR', 'NRU', '674');
INSERT INTO wfg.country VALUES (163, 'Nepal', 'Nepal', 'NP', 'NPL', '977');
INSERT INTO wfg.country VALUES (164, 'Nicaragua', 'Nicaragua', 'NI', 'NIC', '505');
INSERT INTO wfg.country VALUES (165, 'Niger', 'Niger', 'NE', 'NER', '227');
INSERT INTO wfg.country VALUES (166, 'Nigeria', 'Nigeria', 'NG', 'NGA', '234');
INSERT INTO wfg.country VALUES (167, 'Niue', 'Niue', 'NU', 'NIU', '683');
INSERT INTO wfg.country VALUES (168, 'Norway', 'Noruega', 'NO', 'NOR', '47');
INSERT INTO wfg.country VALUES (169, 'New Caledonia', 'Nueva Caledonia', 'NC', 'NCL', '687');
INSERT INTO wfg.country VALUES (170, 'New Zealand', 'Nueva Zelanda', 'NZ', 'NZL', '64');
INSERT INTO wfg.country VALUES (171, 'Oman', 'Omán', 'OM', 'OMN', '968');
INSERT INTO wfg.country VALUES (172, 'Netherlands', 'Países Bajos', 'NL', 'NLD', '31');
INSERT INTO wfg.country VALUES (173, 'Pakistan', 'Pakistán', 'PK', 'PAK', '92');
INSERT INTO wfg.country VALUES (174, 'Palau', 'Palau', 'PW', 'PLW', '680');
INSERT INTO wfg.country VALUES (175, 'Palestine', 'Palestina', 'PS', 'PSE', '970');
INSERT INTO wfg.country VALUES (176, 'Panama', 'Panamá', 'PA', 'PAN', '507');
INSERT INTO wfg.country VALUES (177, 'Papua New Guinea', 'Papúa Nueva Guinea', 'PG', 'PNG', '675');
INSERT INTO wfg.country VALUES (178, 'Paraguay', 'Paraguay', 'PY', 'PRY', '595');
INSERT INTO wfg.country VALUES (179, 'Peru', 'Perú', 'PE', 'PER', '51');
INSERT INTO wfg.country VALUES (180, 'French Polynesia', 'Polinesia Francesa', 'PF', 'PYF', '689');
INSERT INTO wfg.country VALUES (181, 'Poland', 'Polonia', 'PL', 'POL', '48');
INSERT INTO wfg.country VALUES (182, 'Portugal', 'Portugal', 'PT', 'PRT', '351');
INSERT INTO wfg.country VALUES (183, 'Puerto Rico', 'Puerto Rico', 'PR', 'PRI', '1');
INSERT INTO wfg.country VALUES (184, 'Qatar', 'Qatar', 'QA', 'QAT', '974');
INSERT INTO wfg.country VALUES (185, 'United Kingdom', 'Reino Unido', 'GB', 'GBR', '44');
INSERT INTO wfg.country VALUES (186, 'Central African Republic', 'República Centroafricana', 'CF', 'CAF', '236');
INSERT INTO wfg.country VALUES (187, 'Czech Republic', 'República Checa', 'CZ', 'CZE', '420');
INSERT INTO wfg.country VALUES (188, 'Dominican Republic', 'República Dominicana', 'DO', 'DOM', '1 809');
INSERT INTO wfg.country VALUES (189, 'South Sudan', 'República de Sudán del Sur', 'SS', 'SSD', '211');
INSERT INTO wfg.country VALUES (190, 'Réunion', 'Reunión', 'RE', 'REU', '262');
INSERT INTO wfg.country VALUES (191, 'Rwanda', 'Ruanda', 'RW', 'RWA', '250');
INSERT INTO wfg.country VALUES (192, 'Romania', 'Rumanía', 'RO', 'ROU', '40');
INSERT INTO wfg.country VALUES (193, 'Russia', 'Rusia', 'RU', 'RUS', '7');
INSERT INTO wfg.country VALUES (194, 'Western Sahara', 'Sahara Occidental', 'EH', 'ESH', '212');
INSERT INTO wfg.country VALUES (195, 'Samoa', 'Samoa', 'WS', 'WSM', '685');
INSERT INTO wfg.country VALUES (196, 'American Samoa', 'Samoa Americana', 'AS', 'ASM', '1 684');
INSERT INTO wfg.country VALUES (197, 'Saint Barthélemy', 'San Bartolomé', 'BL', 'BLM', '590');
INSERT INTO wfg.country VALUES (198, 'Saint Kitts and Nevis', 'San Cristóbal y Nieves', 'KN', 'KNA', '1 869');
INSERT INTO wfg.country VALUES (199, 'San Marino', 'San Marino', 'SM', 'SMR', '378');
INSERT INTO wfg.country VALUES (200, 'Saint Martin (French part)', 'San Martín (Francia)', 'MF', 'MAF', '1 599');
INSERT INTO wfg.country VALUES (201, 'Saint Pierre and Miquelon', 'San Pedro y Miquelón', 'PM', 'SPM', '508');
INSERT INTO wfg.country VALUES (202, 'Saint Vincent and the Grenadines', 'San Vicente y las Granadinas', 'VC', 'VCT', '1 784');
INSERT INTO wfg.country VALUES (203, 'Ascensión y Tristán de Acuña', 'Santa Elena', 'SH', 'SHN', '290');
INSERT INTO wfg.country VALUES (204, 'Saint Lucia', 'Santa Lucía', 'LC', 'LCA', '1 758');
INSERT INTO wfg.country VALUES (205, 'Sao Tome and Principe', 'Santo Tomé y Príncipe', 'ST', 'STP', '239');
INSERT INTO wfg.country VALUES (206, 'Senegal', 'Senegal', 'SN', 'SEN', '221');
INSERT INTO wfg.country VALUES (207, 'Serbia', 'Serbia', 'RS', 'SRB', '381');
INSERT INTO wfg.country VALUES (208, 'Seychelles', 'Seychelles', 'SC', 'SYC', '248');
INSERT INTO wfg.country VALUES (209, 'Sierra Leone', 'Sierra Leona', 'SL', 'SLE', '232');
INSERT INTO wfg.country VALUES (210, 'Singapore', 'Singapur', 'SG', 'SGP', '65');
INSERT INTO wfg.country VALUES (211, 'Sint Maarten', 'Sint Maarten', 'SX', 'SMX', '1 721');
INSERT INTO wfg.country VALUES (212, 'Syria', 'Siria', 'SY', 'SYR', '963');
INSERT INTO wfg.country VALUES (213, 'Somalia', 'Somalia', 'SO', 'SOM', '252');
INSERT INTO wfg.country VALUES (214, 'Sri Lanka', 'Sri lanka', 'LK', 'LKA', '94');
INSERT INTO wfg.country VALUES (215, 'South Africa', 'Sudáfrica', 'ZA', 'ZAF', '27');
INSERT INTO wfg.country VALUES (216, 'Sudan', 'Sudán', 'SD', 'SDN', '249');
INSERT INTO wfg.country VALUES (217, 'Sweden', 'Suecia', 'SE', 'SWE', '46');
INSERT INTO wfg.country VALUES (218, 'Switzerland', 'Suiza', 'CH', 'CHE', '41');
INSERT INTO wfg.country VALUES (219, 'Suriname', 'Surinám', 'SR', 'SUR', '597');
INSERT INTO wfg.country VALUES (220, 'Svalbard and Jan Mayen', 'Svalbard y Jan Mayen', 'SJ', 'SJM', '47');
INSERT INTO wfg.country VALUES (221, 'Swaziland', 'Swazilandia', 'SZ', 'SWZ', '268');
INSERT INTO wfg.country VALUES (222, 'Tajikistan', 'Tayikistán', 'TJ', 'TJK', '992');
INSERT INTO wfg.country VALUES (223, 'Thailand', 'Tailandia', 'TH', 'THA', '66');
INSERT INTO wfg.country VALUES (224, 'Taiwan', 'Taiwán', 'TW', 'TWN', '886');
INSERT INTO wfg.country VALUES (225, 'Tanzania', 'Tanzania', 'TZ', 'TZA', '255');
INSERT INTO wfg.country VALUES (226, 'British Indian Ocean Territory', 'Territorio Británico del Océano Índico', 'IO', 'IOT', '246');
INSERT INTO wfg.country VALUES (227, 'French Southern Territories', 'Territorios Australes y Antárticas Franceses', 'TF', 'ATF', NULL);
INSERT INTO wfg.country VALUES (228, 'East Timor', 'Timor Oriental', 'TL', 'TLS', '670');
INSERT INTO wfg.country VALUES (229, 'Togo', 'Togo', 'TG', 'TGO', '228');
INSERT INTO wfg.country VALUES (230, 'Tokelau', 'Tokelau', 'TK', 'TKL', '690');
INSERT INTO wfg.country VALUES (231, 'Tonga', 'Tonga', 'TO', 'TON', '676');
INSERT INTO wfg.country VALUES (232, 'Trinidad and Tobago', 'Trinidad y Tobago', 'TT', 'TTO', '1 868');
INSERT INTO wfg.country VALUES (233, 'Tunisia', 'Tunez', 'TN', 'TUN', '216');
INSERT INTO wfg.country VALUES (235, 'Turkey', 'Turquía', 'TR', 'TUR', '90');
INSERT INTO wfg.country VALUES (236, 'Tuvalu', 'Tuvalu', 'TV', 'TUV', '688');
INSERT INTO wfg.country VALUES (237, 'Ukraine', 'Ucrania', 'UA', 'UKR', '380');
INSERT INTO wfg.country VALUES (238, 'Uganda', 'Uganda', 'UG', 'UGA', '256');
INSERT INTO wfg.country VALUES (239, 'Uruguay', 'Uruguay', 'UY', 'URY', '598');
INSERT INTO wfg.country VALUES (240, 'Uzbekistan', 'Uzbekistán', 'UZ', 'UZB', '998');
INSERT INTO wfg.country VALUES (241, 'Vanuatu', 'Vanuatu', 'VU', 'VUT', '678');
INSERT INTO wfg.country VALUES (242, 'Venezuela', 'Venezuela', 'VE', 'VEN', '58');
INSERT INTO wfg.country VALUES (243, 'Vietnam', 'Vietnam', 'VN', 'VNM', '84');
INSERT INTO wfg.country VALUES (244, 'Wallis and Futuna', 'Wallis y Futuna', 'WF', 'WLF', '681');
INSERT INTO wfg.country VALUES (245, 'Yemen', 'Yemen', 'YE', 'YEM', '967');
INSERT INTO wfg.country VALUES (246, 'Djibouti', 'Yibuti', 'DJ', 'DJI', '253');
INSERT INTO wfg.country VALUES (247, 'Zambia', 'Zambia', 'ZM', 'ZMB', '260');
INSERT INTO wfg.country VALUES (248, 'Zimbabwe', 'Zimbabue', 'ZW', 'ZWE', '263');


--
-- PostgreSQL database dump complete
--

